services:
    #PHP Service
    data-validation:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: data-validation
        tty: true
        environment:
            SERVICE_NAME: data-validation
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - yorcreative

networks:
    yorcreative:
        driver: bridge

