name: Linter

on: [ pull_request ]

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --dev

      - name: Fix PHP code style issues
        run: php ./vendor/bin/phpcbf --standard=PSR12 ./src

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling to adhere to PSR12 standards.